name: Python unit-tests

on:
  push:
    branches:
      - devel
      - main
      - release
  pull_request:
    branches:
      - main
      - devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential  # Install build tools

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install dependencies from setup.py

    - name: Run tests
      run: |
        python -m unittest discover -s tests