name: Release
on:
  push:
    branches:
      - release
      - release/*
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false # <--- this
        ref: ${{ github.head_ref }} 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install python-semantic-release

    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: semantic-release  version 

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential  # Install build tools

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install dependencies from setup.py

    - name: Install documentation dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-multiversion sphinx_rtd_theme recommonmark

    - name: Build documentation
      run: |
        cd docs
        sphinx-multiversion . docs/_build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages
        #destination_dir: ${{ github.ref_name }}  # Deploy to a subdirectory named after the branch