name: Release

on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'  # Trigger only when a version tag (e.g., v1.0.0) is pushed


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing version updates and tags

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to ensure versioning works correctly

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      # Run semantic-release to handle versioning
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub token for pushing tags
        run: semantic-release version 

